name: Java CI with Maven
on:
  [push]
  workflow_run:
    workflows: [builSwellServer]
    types:
      - completed


jobs:
  buildSwellServer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build Swell Server
      run: mvn clean install -DskipTests

  testSwellServer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Test Swell Server
      run: mvn clean install
