name: Test swell-server

on:
    workflow_run:
        workflows:
          - Build
        types: 
          - completed
        branches:
            - main

jobs:
  testSwellServer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Test Swell Server
      run: mvn clean install